spring:
  profiles:
    active: dev
  application:
    name: techchallenge01
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    docExpansion: none
tag:
  swagger:
    cliente:
        name: "Cliente"
        description: "API de Clientes"
    produto:
        name: "Produto"
        description: "API de Produtos"
    categoriaproduto:
        name: "Categorias de Produto"
        description: "API de Categorias de Produto"



